"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import { Send, Square } from "lucide-react";

const MAX_CHARS = 4000;

interface ChatInputProps {
  onSend: (message: string) => void;
  onStop?: () => void;
  isTyping: boolean;
  disabled?: boolean;
  placeholder?: string;
  hideDisclaimer?: boolean;
}

export function ChatInput({ onSend, onStop, isTyping, disabled, placeholder, hideDisclaimer }: ChatInputProps) {
  const [input, setInput] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const sendingRef = useRef(false);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 200) + "px";
    }
  }, [input]);

  // Focus textarea on mount and when typing stops
  useEffect(() => {
    if (!isTyping && textareaRef.current) {
      textareaRef.current.focus();
    }
  }, [isTyping]);

  const handleSend = useCallback(() => {
    const trimmed = input.trim();
    if (!trimmed || isTyping || disabled || sendingRef.current) return;
    if (trimmed.length > MAX_CHARS) return;

    sendingRef.current = true;
    onSend(trimmed);
    setInput("");
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }
    // Reset guard after a tick
    setTimeout(() => {
      sendingRef.current = false;
    }, 100);
  }, [input, isTyping, disabled, onSend]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    },
    [handleSend]
  );

  const charCount = input.length;
  const isNearLimit = charCount > MAX_CHARS * 0.8;
  const isOverLimit = charCount > MAX_CHARS;

  return (
    <div className="shrink-0 w-full" role="region" aria-label="Chat input">
      <div className="mx-auto max-w-4xl px-4 pb-3 pt-1">
        <div
          className={`relative flex items-center gap-1.5 bg-secondary/70 rounded-full border transition-all duration-300 pl-5 pr-2 py-2 ${
            isOverLimit
              ? "border-danger shadow-[0_0_0_2px_rgba(239,68,68,0.15)]"
              : "border-border/60 focus-within:border-primary/50 focus-within:shadow-[0_0_0_2px_rgba(37,99,235,0.12)] focus-within:bg-secondary"
          }`}
        >
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => {
              if (e.target.value.length <= MAX_CHARS + 100) {
                setInput(e.target.value);
              }
            }}
            onKeyDown={handleKeyDown}
            placeholder={placeholder || "Ask me anything..."}
            disabled={isTyping || disabled}
            rows={1}
            aria-label="Message input"
            aria-invalid={isOverLimit}
            className="flex-1 bg-transparent text-sm text-foreground placeholder-muted-foreground/60 outline-none resize-none disabled:opacity-50 min-h-[22px] max-h-[180px] leading-relaxed py-0.5"
          />

          {/* Action button — send or stop */}
          <div className="flex items-center shrink-0">
            {isTyping ? (
              <motion.button
                initial={{ scale: 0.8 }}
                animate={{ scale: 1 }}
                onClick={onStop}
                className="w-8 h-8 rounded-full bg-destructive hover:bg-destructive/90 flex items-center justify-center transition-colors active:scale-90"
                title="Stop generating"
                aria-label="Stop generating response"
              >
                <Square className="h-3.5 w-3.5 text-white fill-white" />
              </motion.button>
            ) : (
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.9 }}
                onClick={handleSend}
                disabled={!input.trim() || disabled || isOverLimit}
                className="w-8 h-8 rounded-full bg-gradient-to-r from-primary to-accent flex items-center justify-center shrink-0 disabled:opacity-25 disabled:cursor-not-allowed hover:shadow-md transition-all active:scale-90"
                aria-label="Send message"
              >
                <Send className="h-3.5 w-3.5 text-white" />
              </motion.button>
            )}
          </div>
        </div>

        {/* Bottom row: char count + hints (only when disclaimer is shown, i.e. not on the AI page) */}
        {!hideDisclaimer && (
          <div className="flex items-center justify-between mt-1.5 px-1">
            <p className="text-[10px] text-muted-foreground/60">
              Suresh AI is powered by OpenAI. Responses are generated by AI and may not always be accurate.
            </p>
            <div className="flex items-center gap-2 text-[10px] text-muted-foreground/50">
              {charCount > 0 && (
                <span className={`${isOverLimit ? "text-danger" : isNearLimit ? "text-warning" : ""}`}>
                  {charCount.toLocaleString()}/{MAX_CHARS.toLocaleString()}
                </span>
              )}
              <span className="hidden sm:flex items-center gap-1">
                <kbd className="px-1 py-0.5 rounded bg-secondary border border-border/50 text-[9px] leading-none">Enter</kbd>
                <span>send</span>
              </span>
              <span className="hidden sm:flex items-center gap-1">
                <kbd className="px-1 py-0.5 rounded bg-secondary border border-border/50 text-[9px] leading-none">Shift</kbd>
                <span className="text-muted-foreground/40">+</span>
                <kbd className="px-1 py-0.5 rounded bg-secondary border border-border/50 text-[9px] leading-none">Enter</kbd>
                <span>newline</span>
              </span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
